# Generated by Django 5.2.5 on 2025-08-25 11:24

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daycareprovider',
            name='email_addresses',
            field=models.JSONField(blank=True, default=invoices.models.default_list, help_text='Known email addresses for automatic invoice detection'),
        ),
        migrations.AlterField(
            model_name='daycareprovider',
            name='email_subject_patterns',
            field=models.JSONField(blank=True, default=invoices.models.default_list, help_text='Email subject patterns to identify invoices'),
        ),
    ]
