# Generated by Django 5.2.5 on 2025-08-26 07:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Previous unpaid balance carried forward', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount due including previous balance', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='week_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount due for this week only (excluding previous balance)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, help_text='Legacy field - use total_amount_due instead', max_digits=10),
        ),
    ]
