# Generated by Django 5.2.5 on 2025-08-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_add_enhanced_financial_fields'),
        ('invoices', '0004_invoice_previous_balance_invoice_total_amount_due_and_more'),
    ]

    operations = [
    ]
